//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.23 at 12:48:18 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://market.antonshu.pro/soap/products", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package pro.antonshu.market.soap.products;
